[package]
name = "aoc"
publish.workspace = true
version.workspace = true
edition.workspace = true

[lib]
proc-macro = true

[dependencies]
quote.workspace = true
syn = { workspace = true, features = ["full"] }
